### ISSUE TITLE
Upgrade from 1.5.5 to 1.5.6 break project compilation

### ISSUE THREAD

**Issue by ben-j69** [jainsahab/AndroidSnooper#28]
Hello,

I was using v1.5.5 with okhttp : 
```
// Android Snooper library for Okhttp
    implementation('com.github.jainsahab:Snooper-Okhttp:1.5.5@aar') {
    transitive = true
}
```

When I upgrade to 1.5.6, I can not run my unit tests anymore, do you have an idea of what happened ? Maybe there is a conflict in dependencies ?
```
// Android Snooper library for Okhttp
    implementation('com.github.jainsahab:Snooper-Okhttp:1.5.6@aar') {
    transitive = true
}
```

The error appear when I run `./gradlew app:compilePrimaryDebugUnitTestKotlin` : 
```
> Task :app:compilePrimaryDebugUnitTestKotlin FAILED
e: /Users/benj/Desktop/XXX/XXX-android-client/app/src/test/java/com/wayzup/object/ObjectTestHelper.kt: (3, 27): Unresolved reference: lang3
e: /Users/benj/Desktop/XXX/XXX-android-client/app/src/test/java/com/wayzup/object/ObjectTestHelper.kt: (18, 26): Unresolved reference: SerializationUtils
e: /Users/benj/Desktop/XXX/XXX-android-client/app/src/test/java/com/wayzup/object/ObjectTestHelper.kt: (19, 28): Unresolved reference: SerializationUtils
```

**Comment by jainsahab** [comment]
Hi @ben-j69,

According to the compilation error log, it looks like your project is looking for `commons-lang3` dependency which we have [removed](https://github.com/jainsahab/AndroidSnooper/compare/V1.5.5...V1.5.6) in 1.5.6. Your project was probably using a transitive dependency this way. if you want to use this you need to add it explicitly in your codebase.

**Comment by ben-j69** [comment]
@jainsahab thanks, it is solved, I should have find alone, sorry to waste your time!
